package org.greenstone.backend.persistence.entity;

public enum JobActivityType { CREATED, STATUS_CHANGED, SCHEDULE_CHANGED, ASSIGNMENT_CHANGED, DETAILS_UPDATED, PHOTO_ADDED, CHECKLIST_UPDATED, SIGNOFF_RECORDED, INVOICE_CREATED, NOTIFICATION_SENT, NOTIFICATION_FAILED }
