import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { AlertTriangle, ArrowLeft, CheckCircle2, Download, LoaderCircle, ReceiptText, Save } from 'lucide-react'
import { downloadInvoicePdf, listInvoices, updateInvoice, type Invoice, type InvoiceStatus } from './api/adminOperations'
import './AdminOperations.css'
const labels:Record<InvoiceStatus,string>={DRAFT:'Draft',SENT:'Sent',PART_PAID:'Part paid',PAID:'Paid',VOID:'Void'}
const money=(v:number)=>new Intl.NumberFormat('en-NZ',{style:'currency',currency:'NZD'}).format(v)
const date=(v:string)=>new Intl.DateTimeFormat('en-NZ',{dateStyle:'medium'}).format(new Date(`${v}T00:00:00`))
export default function AdminInvoices({onSessionExpired}:{onSessionExpired:()=>void}){
 const [items,setItems]=useState<Invoice[]>([]);const [selected,setSelected]=useState<Invoice|null>(null);const [draft,setDraft]=useState({status:'DRAFT' as InvoiceStatus,amountPaid:0,dueDate:'',paymentReference:'',notes:''});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [success,setSuccess]=useState('')
 const handle=useCallback((e:unknown,f:string)=>{if(e&&typeof e==='object'&&'status'in e&&e.status===401)onSessionExpired();else setError(e instanceof Error?e.message:f)},[onSessionExpired])
 const load=useCallback(()=>{setLoading(true);listInvoices().then(result=>{setItems(result);const initial=new URLSearchParams(window.location.search).get('invoice');if(initial){const found=result.find(i=>i.id===initial);if(found)open(found)}}).catch(e=>handle(e,'Invoices could not be loaded.')).finally(()=>setLoading(false))},[handle])
 useEffect(()=>{const t=window.setTimeout(load);return()=>window.clearTimeout(t)},[load])
 function open(i:Invoice){setSelected(i);setDraft({status:i.status,amountPaid:i.amountPaid,dueDate:i.dueDate,paymentReference:i.paymentReference??'',notes:i.notes??''});setError('');setSuccess('')}
 async function save(e:FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{const updated=await updateInvoice(selected.id,{...draft,paymentReference:draft.paymentReference.trim()||null,notes:draft.notes.trim()||null,version:selected.version});open(updated);await listInvoices().then(setItems);setSuccess('Invoice and payment record saved.')}catch(c){handle(c,'Invoice could not be saved.')}finally{setBusy(false)}}
 async function pdf(){if(!selected)return;setBusy(true);try{const blob=await downloadInvoicePdf(selected.id);const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`${selected.invoiceNumber}.pdf`;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(c){handle(c,'Invoice PDF could not be downloaded.')}finally{setBusy(false)}}
 if(selected)return <section className="ops-page"><button className="ops-back" onClick={()=>setSelected(null)}><ArrowLeft/>Back to invoices</button><header className="ops-heading"><div><span className="admin-eyebrow">{selected.invoiceNumber}</span><h1>{selected.customerName}</h1><p>{selected.jobNumber} · {selected.propertyAddress||'No address supplied'}</p></div><span className={`invoice-status invoice-status--${selected.status.toLowerCase()}`}>{labels[selected.status]}</span></header>{error&&<div className="ops-alert error"><AlertTriangle/>{error}</div>}{success&&<div className="ops-alert success"><CheckCircle2/>{success}</div>}<div className="invoice-detail"><form onSubmit={save}><div className="invoice-total"><span>Balance due</span><strong>{money(selected.balanceDue)}</strong><small>Total {money(selected.total)} · Paid {money(selected.amountPaid)}</small></div><div className="invoice-fields"><label><span>Status</span><select value={draft.status} onChange={e=>setDraft({...draft,status:e.target.value as InvoiceStatus})} disabled={selected.status==='VOID'}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label><span>Amount paid</span><input type="number" min="0" max={selected.total} step="0.01" value={draft.amountPaid} onChange={e=>setDraft({...draft,amountPaid:Number(e.target.value)})}/></label><label><span>Due date</span><input type="date" value={draft.dueDate} onChange={e=>setDraft({...draft,dueDate:e.target.value})}/></label><label><span>Payment reference</span><input maxLength={200} value={draft.paymentReference} onChange={e=>setDraft({...draft,paymentReference:e.target.value})}/></label></div><label className="invoice-notes"><span>Internal payment notes</span><textarea rows={5} maxLength={10000} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label><div className="invoice-actions"><button type="submit" disabled={busy}><Save/>{busy?'Saving…':'Save invoice'}</button><button type="button" onClick={pdf} disabled={busy}><Download/>Download PDF</button></div></form><aside><span className="admin-eyebrow">Billing details</span><h2>{selected.customerName}</h2><a href={`mailto:${selected.customerEmail}`}>{selected.customerEmail}</a><dl><div><dt>Subtotal</dt><dd>{money(selected.subtotal)}</dd></div><div><dt>GST</dt><dd>{money(selected.gstAmount)}</dd></div><div><dt>Due</dt><dd>{date(selected.dueDate)}</dd></div></dl></aside></div></section>
 return <section className="ops-page"><header className="ops-heading"><div><span className="admin-eyebrow">Finance</span><h1>Invoices and payments</h1><p>Generate branded invoices from completed jobs and keep collection status current.</p></div><ReceiptText/></header>{error&&<div className="ops-alert error"><AlertTriangle/>{error}</div>}{loading?<div className="ops-loading"><LoaderCircle className="admin-spinner"/>Loading invoices…</div>:items.length?<div className="invoice-list"><div><span>Invoice</span><span>Customer</span><span>Due</span><span>Balance</span><span>Status</span></div>{items.map(i=><button key={i.id} onClick={()=>open(i)}><span><strong>{i.invoiceNumber}</strong><small>{i.jobNumber}</small></span><span><strong>{i.customerName}</strong><small>{i.customerEmail}</small></span><span>{date(i.dueDate)}</span><strong>{money(i.balanceDue)}</strong><span className={`invoice-status invoice-status--${i.status.toLowerCase()}`}>{labels[i.status]}</span></button>)}</div>:<div className="ops-empty"><ReceiptText/><h2>No invoices yet</h2><p>Complete and sign off a job, then create its invoice from the job record.</p></div>}</section>
}
