import { useCallback, useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { AlertTriangle, ArrowLeft, BriefcaseBusiness, CalendarDays, CalendarRange, Camera, CheckCircle2, Clock3, Image, List, LoaderCircle, Mail, MapPin, PenLine, Phone, ReceiptText, Save, Search, Upload, UserRound } from 'lucide-react'
import { getJob, getJobPhoto, listJobs, recordJobSignoff, updateJob, updateJobChecklist, uploadJobPhoto, type JobDetail, type JobPage, type JobPhotoPhase, type JobStatus, type JobSummary } from './api/adminJobs'
import { createInvoice } from './api/adminOperations'
import './AdminJobs.css'

const statusLabels: Record<JobStatus, string> = { PLANNED: 'Planned', SCHEDULED: 'Scheduled', IN_PROGRESS: 'In progress', ON_HOLD: 'On hold', COMPLETED: 'Completed', CANCELLED: 'Cancelled' }
const phaseLabels: Record<JobPhotoPhase, string> = { BEFORE: 'Before', PROGRESS: 'Progress', COMPLETED: 'Completed' }
const emptyPage: JobPage = { items: [], staff: [], metrics: { planned: 0, scheduled: 0, inProgress: 0, completed: 0 } }
function date(value: string | null) { return value ? new Intl.DateTimeFormat('en-NZ', { dateStyle: 'medium', timeZone: 'Pacific/Auckland' }).format(new Date(`${value}T00:00:00`)) : 'Not scheduled' }
function dateTime(value: string) { return new Intl.DateTimeFormat('en-NZ', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Pacific/Auckland' }).format(new Date(value)) }
function money(value: number) { return new Intl.NumberFormat('en-NZ', { style: 'currency', currency: 'NZD' }).format(value) }

function JobCalendar({ jobs, onOpen }: { jobs: JobSummary[]; onOpen: (id: string) => void }) {
  const [month, setMonth] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1) })
  const days = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const offset = (month.getDay() + 6) % 7
  const key = (day: number) => `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`
  return <section className="job-calendar"><header><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>← Previous</button><h2>{month.toLocaleDateString('en-NZ', { month: 'long', year: 'numeric' })}</h2><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>Next →</button></header><div className="job-calendar-week">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d => <span key={d}>{d}</span>)}</div><div className="job-calendar-grid">{Array.from({ length: offset }, (_, i) => <div className="outside" key={`o${i}`} />)}{Array.from({ length: days }, (_, i) => i + 1).map(day => { const dayKey = key(day); const work = jobs.filter(j => j.scheduledStartDate && j.scheduledStartDate <= dayKey && (j.scheduledEndDate || j.scheduledStartDate) >= dayKey); return <div key={day}><strong>{day}</strong>{work.map(j => <button key={j.id} onClick={() => onOpen(j.id)}><span>{j.customerName}</span><small>{j.assignedDisplayName || 'Unassigned'}</small></button>)}</div> })}</div></section>
}

function Photo({ jobId, photo }: { jobId: string; photo: JobDetail['photos'][number] }) {
  const [url, setUrl] = useState('')
  useEffect(() => { let active = true; let objectUrl = ''; getJobPhoto(jobId, photo.id).then((blob) => { if (!active) return; objectUrl = URL.createObjectURL(blob); setUrl(objectUrl) }).catch(() => {}); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl) } }, [jobId, photo.id])
  return <article className="job-photo">{url ? <img src={url} alt={`${phaseLabels[photo.phase]} work photo`} /> : <div><LoaderCircle className="admin-spinner" /></div>}<span>{phaseLabels[photo.phase]}</span><small>{photo.filename}</small></article>
}

export default function AdminJobs({ onSessionExpired }: { onSessionExpired: () => void }) {
  const initialId = new URLSearchParams(window.location.search).get('job')
  const [page, setPage] = useState<JobPage>(emptyPage)
  const [selected, setSelected] = useState<JobDetail | null>(null)
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [assignment, setAssignment] = useState('')
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const [draft, setDraft] = useState({ status: 'PLANNED' as JobStatus, assignedAdminId: '', scheduledStartDate: '', scheduledEndDate: '', siteInstructions: '', internalNotes: '' })
  const [photoPhase, setPhotoPhase] = useState<JobPhotoPhase>('PROGRESS')
  const [viewMode, setViewMode] = useState<'list' | 'calendar'>('list')
  const [signoffName, setSignoffName] = useState('')

  const apply = useCallback((job: JobDetail) => { setSelected(job); setDraft({ status: job.status, assignedAdminId: job.assignedAdminId ?? '', scheduledStartDate: job.scheduledStartDate ?? '', scheduledEndDate: job.scheduledEndDate ?? '', siteInstructions: job.siteInstructions ?? '', internalNotes: job.internalNotes ?? '' }); setError('') }, [])
  const handle = useCallback((caught: unknown, fallback: string) => { if (caught && typeof caught === 'object' && 'status' in caught && caught.status === 401) onSessionExpired(); else setError(caught instanceof Error ? caught.message : fallback) }, [onSessionExpired])
  const load = useCallback(async (q = query, s = status, a = assignment) => { setLoading(true); try { setPage(await listJobs(q, s, a)); setError('') } catch (caught) { handle(caught, 'Jobs could not be loaded.') } finally { setLoading(false) } }, [assignment, handle, query, status])

  useEffect(() => {
    const timer = window.setTimeout(() => {
      listJobs().then((result) => { setPage(result); setError('') })
        .catch((caught) => handle(caught, 'Jobs could not be loaded.'))
        .finally(() => setLoading(false))
      if (initialId) getJob(initialId).then(apply).catch((caught) => handle(caught, 'The requested job could not be loaded.'))
    })
    return () => window.clearTimeout(timer)
  }, [apply, handle, initialId])
  const dirty = useMemo(() => selected && (draft.status !== selected.status || draft.assignedAdminId !== (selected.assignedAdminId ?? '') || draft.scheduledStartDate !== (selected.scheduledStartDate ?? '') || draft.scheduledEndDate !== (selected.scheduledEndDate ?? '') || draft.siteInstructions !== (selected.siteInstructions ?? '') || draft.internalNotes !== (selected.internalNotes ?? '')), [draft, selected])

  async function save(event: FormEvent) { event.preventDefault(); if (!selected) return; if (draft.scheduledStartDate && draft.scheduledEndDate && draft.scheduledEndDate < draft.scheduledStartDate) { setError('Scheduled completion cannot be before the start date.'); return } if (draft.status === 'SCHEDULED' && (!draft.scheduledStartDate || !draft.scheduledEndDate)) { setError('Scheduled jobs need both dates.'); return } setBusy('save'); setError(''); setSuccess(''); try { const updated = await updateJob(selected.id, { status: draft.status, assignedAdminId: draft.assignedAdminId || null, scheduledStartDate: draft.scheduledStartDate || null, scheduledEndDate: draft.scheduledEndDate || null, siteInstructions: draft.siteInstructions.trim() || null, internalNotes: draft.internalNotes.trim() || null, version: selected.version }); apply(updated); await load(); setSuccess('Job changes saved.') } catch (caught) { handle(caught, 'The job could not be saved.') } finally { setBusy('') } }
  async function upload(files: FileList | null) { if (!selected || !files?.length) return; setBusy('photo'); setError(''); try { let current = selected; for (const file of Array.from(files)) current = await uploadJobPhoto(current.id, photoPhase, file); apply(current); await load(); setSuccess(`${files.length} site photo${files.length === 1 ? '' : 's'} added.`) } catch (caught) { handle(caught, 'The site photo could not be uploaded.') } finally { setBusy('') } }
  async function toggleChecklist(item: JobDetail['checklist'][number]) { if (!selected) return; setBusy(item.id); setError(''); try { apply(await updateJobChecklist(selected.id, item.id, !item.completed)); setSuccess('Completion checklist updated.') } catch (caught) { handle(caught, 'The checklist could not be updated.') } finally { setBusy('') } }
  async function signoff(event: FormEvent) { event.preventDefault(); if (!selected || !signoffName.trim()) return; setBusy('signoff'); setError(''); try { apply(await recordJobSignoff(selected.id, signoffName)); setSignoffName(''); setSuccess('Customer sign-off recorded. The job can now be completed.') } catch (caught) { handle(caught, 'Customer sign-off could not be recorded.') } finally { setBusy('') } }
  async function invoice() { if (!selected) return; setBusy('invoice'); setError(''); try { const result = await createInvoice(selected.id); window.location.href = `/admin/?section=invoices&invoice=${result.id}` } catch (caught) { handle(caught, 'The invoice could not be created.') } finally { setBusy('') } }

  if (selected) return <section className="jobs-page">
    <button type="button" className="jobs-back" onClick={() => { setSelected(null); const url = new URL(window.location.href); url.searchParams.delete('job'); window.history.replaceState({}, '', url) }}><ArrowLeft /> Back to jobs</button>
    <header className="job-detail-header"><div><span className="admin-eyebrow">{selected.jobNumber}</span><h1>{selected.title}</h1><p><MapPin />{selected.propertyAddress || 'Property address not supplied'}</p></div><span className={`job-status job-status--${selected.status.toLowerCase()}`}>{statusLabels[selected.status]}</span></header>
    {error && <div className="jobs-alert error"><AlertTriangle />{error}</div>}{success && <div className="jobs-alert success"><CheckCircle2 />{success}</div>}
    <div className="job-detail-layout"><form className="job-workflow" onSubmit={save}><section><div className="job-section-title"><span>Operations</span><h2>Schedule and ownership</h2></div><div className="job-form-grid"><label><span>Status</span><select value={draft.status} onChange={(e) => setDraft({ ...draft, status: e.target.value as JobStatus })} disabled={selected.status === 'COMPLETED' || selected.status === 'CANCELLED'}>{Object.entries(statusLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></label><label><span>Assigned crew member</span><select value={draft.assignedAdminId} onChange={(e) => setDraft({ ...draft, assignedAdminId: e.target.value })}><option value="">Unassigned</option>{page.staff.filter((s) => s.enabled).map((s) => <option value={s.id} key={s.id}>{s.displayName}</option>)}</select></label><label><span>Start date</span><input type="date" value={draft.scheduledStartDate} onChange={(e) => setDraft({ ...draft, scheduledStartDate: e.target.value })} /></label><label><span>Completion date</span><input type="date" value={draft.scheduledEndDate} onChange={(e) => setDraft({ ...draft, scheduledEndDate: e.target.value })} /></label></div><label className="job-textarea"><span>Site instructions</span><textarea rows={5} maxLength={10000} value={draft.siteInstructions} onChange={(e) => setDraft({ ...draft, siteInstructions: e.target.value })} placeholder="Access, parking, colour confirmation, hazards and customer arrangements…" /></label><label className="job-textarea"><span>Internal notes</span><textarea rows={5} maxLength={10000} value={draft.internalNotes} onChange={(e) => setDraft({ ...draft, internalNotes: e.target.value })} placeholder="Private information for the Greenstone team…" /></label><button className="job-save" type="submit" disabled={!dirty || Boolean(busy)}>{busy === 'save' ? <LoaderCircle className="admin-spinner" /> : <Save />} {dirty ? 'Save job changes' : 'Changes saved'}</button></section>
      <section><div className="job-section-title"><span>Completion</span><h2>Quality checklist and sign-off</h2></div><div className="job-checklist">{selected.checklist.map(item => <label key={item.id} className={item.completed ? 'done' : ''}><input type="checkbox" checked={item.completed} disabled={Boolean(busy) || selected.status === 'COMPLETED' || selected.status === 'CANCELLED'} onChange={() => void toggleChecklist(item)} /><span><strong>{item.label}</strong>{item.completedAt && <small>{item.completedBy} · {dateTime(item.completedAt)}</small>}</span></label>)}</div>{selected.customerSignoffAt ? <div className="job-signoff-complete"><CheckCircle2/><div><strong>Signed off by {selected.customerSignoffName}</strong><span>{dateTime(selected.customerSignoffAt)}</span></div></div> : <form className="job-signoff" onSubmit={signoff}><PenLine/><div><strong>Record customer walkthrough approval</strong><span>Complete every checklist item first.</span></div><input aria-label="Customer name" placeholder="Customer full name" maxLength={200} value={signoffName} onChange={e => setSignoffName(e.target.value)} /><button disabled={Boolean(busy) || !signoffName.trim() || selected.checklist.some(i => !i.completed)}>Record sign-off</button></form>}<div className="job-invoice-action"><ReceiptText/><div><strong>{selected.invoice ? selected.invoice.invoiceNumber : 'Ready for invoicing'}</strong><span>{selected.invoice ? `${selected.invoice.status.replace('_',' ')} · ${money(selected.invoice.balanceDue)} due` : 'Invoices become available after the job is completed.'}</span></div><button type="button" onClick={() => void invoice()} disabled={Boolean(busy) || selected.status !== 'COMPLETED'}>{selected.invoice ? 'Open invoice' : 'Create invoice'}</button></div></section>
      <section><div className="job-section-title"><span>Site record</span><h2>Work photos</h2></div><div className="job-photo-upload"><select value={photoPhase} onChange={(e) => setPhotoPhase(e.target.value as JobPhotoPhase)}>{Object.entries(phaseLabels).map(([v, l]) => <option value={v} key={v}>{l}</option>)}</select><label className={busy ? 'disabled' : ''}><Upload />{busy === 'photo' ? 'Uploading…' : 'Add photos'}<input type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" multiple disabled={Boolean(busy)} onChange={(e) => void upload(e.target.files)} /></label><span>JPEG, PNG, WebP, HEIC · 5 MB each</span></div>{selected.photos.length ? <div className="job-photo-grid">{selected.photos.map((p) => <Photo key={p.id} jobId={selected.id} photo={p} />)}</div> : <div className="job-empty-photos"><Camera /><p>No site photos have been added.</p></div>}</section>
      <section><div className="job-section-title"><span>Record</span><h2>Activity timeline</h2></div><div className="job-timeline">{selected.activities.map((a) => <article key={a.id}><Clock3 /><div><strong>{a.summary}</strong><span>{a.actorDisplayName} · {dateTime(a.createdAt)}</span>{a.noteBody && <p>{a.noteBody}</p>}</div></article>)}</div></section></form>
      <aside className="job-summary"><section><span className="admin-eyebrow">Customer</span><h2>{selected.customerName}</h2><a href={`mailto:${selected.customerEmail}`}><Mail />{selected.customerEmail}</a>{selected.customerPhone && <a href={`tel:${selected.customerPhone}`}><Phone />{selected.customerPhone}</a>}</section><section><span className="admin-eyebrow">Accepted quote</span><strong>{selected.quoteNumber}</strong><b>{money(selected.quoteTotal)}</b></section><section><span className="admin-eyebrow">Scope</span><p>{selected.scope}</p></section></aside></div>
  </section>

  return <section className="jobs-page"><header className="jobs-heading"><div><span className="admin-eyebrow">Operations</span><h1>Painting jobs</h1><p>Schedule accepted work, assign the team and keep every site record together.</p></div><div className="job-view-toggle"><button className={viewMode==='list'?'active':''} onClick={() => setViewMode('list')}><List/>List</button><button className={viewMode==='calendar'?'active':''} onClick={() => setViewMode('calendar')}><CalendarRange/>Calendar</button></div></header>
    <div className="job-metrics"><article><span>Planned</span><strong>{page.metrics.planned}</strong></article><article><span>Scheduled</span><strong>{page.metrics.scheduled}</strong></article><article><span>In progress</span><strong>{page.metrics.inProgress}</strong></article><article><span>Completed</span><strong>{page.metrics.completed}</strong></article></div>
    <form className="job-filters" onSubmit={(e) => { e.preventDefault(); void load() }}><label><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Job, customer, address or project" /></label><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option>{Object.entries(statusLabels).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><select value={assignment} onChange={(e) => setAssignment(e.target.value)}><option value="">All crew</option><option value="mine">Assigned to me</option><option value="unassigned">Unassigned</option>{page.staff.filter((s) => s.enabled).map((s) => <option key={s.id} value={s.id}>{s.displayName}</option>)}</select><button type="submit">Apply filters</button></form>
    {error && <div className="jobs-alert error"><AlertTriangle />{error}</div>}{loading ? <div className="jobs-loading"><LoaderCircle className="admin-spinner" /> Loading jobs…</div> : viewMode === 'calendar' ? <JobCalendar jobs={page.items} onOpen={(id) => { setBusy('load'); getJob(id).then(apply).catch((caught) => handle(caught, 'The job could not be loaded.')).finally(() => setBusy('')) }} /> : page.items.length ? <div className="jobs-table"><div className="jobs-table-head"><span>Job</span><span>Schedule</span><span>Crew</span><span>Status</span><span></span></div>{page.items.map((job) => <button key={job.id} type="button" onClick={() => { setBusy('load'); getJob(job.id).then(apply).catch((caught) => handle(caught, 'The job could not be loaded.')).finally(() => setBusy('')) }}><span><small>{job.jobNumber}</small><strong>{job.customerName}</strong><em>{job.title}</em><i><MapPin />{job.propertyAddress || 'No address'}</i></span><span><CalendarDays /><strong>{date(job.scheduledStartDate)}</strong><small>{job.scheduledEndDate ? `to ${date(job.scheduledEndDate)}` : ''}</small></span><span><UserRound /><strong>{job.assignedDisplayName || 'Unassigned'}</strong><small><Image />{job.photoCount} photos</small></span><span className={`job-status job-status--${job.status.toLowerCase()}`}>{statusLabels[job.status]}</span><span>→</span></button>)}</div> : <div className="jobs-empty"><BriefcaseBusiness /><h2>No jobs match these filters</h2><p>Accepted quotes can be converted into jobs from the enquiry quote workspace.</p></div>}
  </section>
}
